---
- hosts: nc-data
  become: yes
  tasks:
    - name: Enable rpcbind
      service:
        name: rpcbind
        state: started
        enabled: yes
    - name: Enable NFS Server
      service:
        name: nfs-server
        state: started
        enabled: yes
    - name: Allow firewall ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - nfs
        - rpc-bind
        - mountd
    - name: Create NFS directory
      file:
        path: /var/data/nc-web
        state: directory
        owner: root
        group: root
    - name: Create NFS Exports
      template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
      notify:
        - Restart NFS Server
  handlers:
    - name: Restart NFS Server
      service:
        name: nfs-server
        state: restarted
