---
- hosts: nc-db
  become: yes
  vars:
    mariadb_root_password: password
    mariadb_nextcloud_password: password
  tasks:
    - name: Install mariaDB Ansible Packages
      package:
        name: python3-PyMySQL
        state: present
    - name: Install mariaDB
      package:
        name: mariadb-server
        state: present
    - name: Enable mariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Firewall for mysql
      firewalld:
        service: mysql
        permanent: yes
        state: enabled
    - name: Set mariaDB root password
      mysql_user:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        check_implicit_admin: yes
        user: root
        password: "{{ mariadb_root_password }}"
        priv: "*.*:ALL,GRANT"
        host: "{{ item }}"
      with_items:
        - "{{ ansible_fqdn }}"
        - "::1"
        - "127.0.0.1"
        - "localhost"

    - name: Remove mariaDB anonymous users
      mysql_user:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        name: ''
        host_all: yes
        state: absent

    - name: Remove test database and access to it
      mysql_db:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        name: test
        state: absent

    - name: Create nextcloud Database
      mysql_db:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        name: nextcloud
        state: present

    - name: Create nextcloud Database User
      mysql_user:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        user: nextcloud
        password: "{{ mariadb_nextcloud_password }}"
        priv: "nextcloud.*:ALL"
        host: "{{ item }}"
      loop:
        - "*"
        - "%"
